# Generated by Django 4.1.5 on 2023-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(choices=[('Purnea', 'Purnea'), ('Patna', 'Patna'), ('Bhagalpur', 'Bhagalpur'), ('Bhopal', 'Bhopal'), ('indore', 'indore'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Goa', 'Goa'), ('Jalandher', 'Jalandher'), ('Dharbhanga', 'Dharbhanga'), ('Rachi', 'Rachi')], max_length=123)),
            ],
        ),
    ]
