# Generated by Django 4.1.5 on 2023-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
    ]
